apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics.fullname" . }}
  namespace: {{ include "analytics.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.serverPort }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.serverPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.useExistingConfigMap }}
            - secretRef:
                name: {{ .Values.config.useExistingSecret }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}