apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: urlshort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-pod-reader
  namespace: urlshort
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pod-reader-binding
  namespace: urlshort
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: urlshort
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-pod-reader