apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: urlshort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: urlshort/api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: urlshort-config
            - secretRef:
                name: urlshort-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: urlshort
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP