{
 "title": "Redirect",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(redirect_cache_hit_total[5m]))/ (sum(rate(redirect_cache_hit_total[5m])) +  sum(rate(redirect_cache_miss_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirect p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket{job=\"redirect\",uri!~\"/actuator.*\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirect p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"redirect\",uri!~\"/actuator.*\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirect total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"redirect\",uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Overview",
 "time": { "from": "2026-04-10T21:51:59.517Z", "to": "2026-04-10T23:26:05.991Z" },
 "panels": [
  {
   "title": "API 5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"api-stable\",status=~\"5..\",uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"api-stable\",uri!~\"/actuator.*\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"api-stable\",uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirect p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket{job=\"redirect\",uri!~\"/actuator.*\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirect RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"redirect\",uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}