server:
  port: 8080
cassandra:
  contactPoints: "127.0.0.1"
  port: 9042
  datacenter: "dc1"
  keyspace: "urlshortener"
  writeConsistency: LOCAL_ONE
  readConsistency: LOCAL_ONE
logging:
  level:
    com.datastax.oss.driver.internal.core.cql: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true