spring:
  application:
    name: api

server:
  port: 8080
cassandra:
  contactPoints: ${CASSANDRA_CONTACTPOINTS:127.0.0.1}
  port: ${CASSANDRA_PORT:9042}
  datacenter: ${CASSANDRA_DATACENTER:dc1}
  keyspace: ${CASSANDRA_KEYSPACE:urlshortener}
  writeConsistency: LOCAL_ONE
  readConsistency: LOCAL_ONE

logging:
  level:
    com.datastax.oss.driver.internal.core.cql: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      service: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s,2s