{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "redirect.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "redirect.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpaBehavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        - type: Percent
          value: {{ .Values.hpaBehavior.scaleUp.percent }}
          periodSeconds: {{ .Values.hpaBehavior.scaleUp.periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpaBehavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        - type: Percent
          value: {{ .Values.hpaBehavior.scaleDown.percent }}
          periodSeconds: {{ .Values.hpaBehavior.scaleDown.periodSeconds }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- if .Values.customMetrics.enabled }}
    - type: Pods
      pods:
        metric:
          name: {{ .Values.customMetrics.requestsPerSecond.metricName }}
        target:
          type: AverageValue
          averageValue: {{ .Values.customMetrics.requestsPerSecond.averageValue | quote }}
    {{- end }}
{{- end }}