apiVersion: v1
kind: Service
metadata:
  name: redirect
  namespace: {{ include "redirect.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redirect
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http