---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: urlshort
data:
  app-alerts.yml: |
    groups:
      - name: urlshort-app
        rules:
          - alert: ApiHighP99Latency
            expr: |
              histogram_quantile(
                0.99,
                sum(rate(http_request_duration_seconds_bucket{service="api"}[5m])) by (le)
              ) > 0.5
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "API p99 latency is high"
              description: "API p99 latency has been above 500ms for 10 minutes."

          - alert: RedirectHighP99Latency
            expr: |
              histogram_quantile(
                0.99,
                sum(rate(http_request_duration_seconds_bucket{job="redirect"}[5m])) by (le)
              ) > 0.25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Redirect p99 latency is high"
              description: "Redirect p99 latency has been above 250ms for 10 minutes."

          - alert: ApiHigh5xxRate
            expr: |
              (
                sum(rate(http_request_duration_seconds_count{service="api",status=~"5.."}[5m]))
                /
                sum(rate(http_request_duration_seconds_count{service="api"}[5m]))
              ) > 0.02
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "API 5xx rate is high"
              description: "API 5xx ratio has been above 2% for 5 minutes."

          - alert: RedirectHigh5xxRate
            expr: |
              (
                sum(rate(http_request_duration_seconds_count{job="redirect",status=~"5.."}[5m]))
                /
                sum(rate(http_request_duration_seconds_count{job="redirect"}[5m]))
              ) > 0.02
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Redirect 5xx rate is high"
              description: "Redirect 5xx ratio has been above 2% for 5 minutes."

#          - alert: KafkaLagHigh
#            expr: kafka_consumergroup_lag_sum{consumergroup="redirect-analytics"} > 1000
#            for: 10m
#            labels:
#              severity: warning
#            annotations:
#              summary: "Kafka lag is high"
#              description: "Consumer lag for redirect-analytics has been above 1000 for 10 minutes."
